#pragma once

#define UI_ELEMENT_DEFAULT_COLOUR Vector4(1,1,1,1)
#define UI_ELEMENT_DEBUGINFO_COLOUR Vector4(0.5,0.5,0,1)
#define UI_ELEMENT_TIP_COLOUR Vector4(0.5,1,0.5,1)
#define UI_ELEMENT_DEBUGINFO_X_OFFSET 0
#define UI_ELEMENT_DEBUGINFO_Y_OFFSET 0
#define UI_ELEMENT_BOTTOM_X_OFFSET 0
#define UI_ELEMENT_BOTTOM_Y_OFFSET 86
#define UI_ELEMENT_BOTTOM_TIP_Y_OFFSET 10

#define GO_COLOUR_MAIN Vector4(1,1,0,1)
#define GO_COLOUR_INTERACTIBALE Vector4(0.3,0.3,0.8,1)
#define GO_COLOUR_SELECTED Vector4(0,0.8,0,1)
